# Generated by Django 6.0.5 on 2026-06-12 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('parking_sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parking_sites',
        ),
        migrations.AddField(
            model_name='user',
            name='parking_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='parking_sites.parkingsite'),
        ),
    ]
