# Generated by Django 6.0.5 on 2026-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('system_type', models.CharField(choices=[('DESIGNA', 'Designa'), ('DATAPARK', 'Datapark'), ('ZEAG', 'Zeag'), ('MEYPAR', 'Meypar')], max_length=50)),
                ('base_url', models.URLField(blank=True)),
                ('auth_type', models.CharField(choices=[('NONE', 'Sin autenticación'), ('BASIC', 'Autenticación básica'), ('TOKEN', 'Token de autenticación')], default='NONE', max_length=30)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('encrypted_password', models.TextField(blank=True)),
                ('encrypted_token', models.TextField(blank=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Integracion',
                'verbose_name_plural': 'Configuraciones de Integracion',
            },
        ),
    ]
