# Generated by Django 6.0.5 on 2026-06-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantIntegrationIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiers', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_identities', to='integrations.integrationconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_identities', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Identidad de Locatario por Integración',
                'verbose_name_plural': 'Identidades de Locatario por Integración',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'integration'), name='uniq_tenant_integration_identity')],
            },
        ),
    ]
