# Generated by Django 6.0.5 on 2026-06-23 18:05

import apps.integrations.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_tenantintegrationidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='encrypted_password',
            field=apps.integrations.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='encrypted_token',
            field=apps.integrations.fields.EncryptedTextField(blank=True),
        ),
    ]
