# Generated by Django 6.0.5 on 2026-06-12 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_sites', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('external_code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_sites', models.ManyToManyField(blank=True, related_name='validation_types', to='parking_sites.parkingsite')),
                ('tenants', models.ManyToManyField(blank=True, related_name='validation_types', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tipo de Validacion',
                'verbose_name_plural': 'Tipos de Validacion',
            },
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=100)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('external_system', models.CharField(max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=150)),
                ('external_status', models.CharField(blank=True, max_length=50)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('was_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_logs', to='parking_sites.parkingsite')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_logs', to=settings.AUTH_USER_MODEL)),
                ('validation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='validations.validationtype')),
            ],
            options={
                'verbose_name': 'Log de Validacion',
                'verbose_name_plural': 'Logs de Validacion',
                'indexes': [models.Index(fields=['ticket_number'], name='validations_ticket__4d853a_idx'), models.Index(fields=['created_at'], name='validations_created_beb98e_idx'), models.Index(fields=['parking_site', 'created_at'], name='validations_parking_5c948e_idx')],
            },
        ),
    ]
