# Generated by Django 6.0.5 on 2026-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationtype',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('time', 'Tiempo'), ('percentage', 'Porcentaje'), ('fixed_rate', 'Tarifa fija'), ('courtesy', 'Cortesía')], default='', max_length=20),
        ),
    ]
