# Generated by Django 6.0.5 on 2026-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('trade_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_sites', models.ManyToManyField(blank=True, related_name='tenants', to='parking_sites.parkingsite')),
            ],
            options={
                'verbose_name': 'Locatario',
                'verbose_name_plural': 'Locatarios',
            },
        ),
    ]
