from .base import *

DEBUG = False

AlLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True